# Generated by Django 3.2.12 on 2024-02-17 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Nagaland', 'Nagaland'), ('Jharkhand', 'Jharkhand'), ('Lakshadweep', 'Lakshadweep'), ('Uttarakhand', 'Uttarakhand'), ('Meghalaya', 'Meghalaya'), ('Sikkim', 'Sikkim'), ('West Bengal', 'West Bengal'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Odisha', 'Odisha'), ('Telangana', 'Telangana'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Mizoram', 'Mizoram'), ('Delhi', 'Delhi'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Chandigarh', 'Chandigarh'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Gujarat', 'Gujarat'), ('Manipur', 'Manipur'), ('Haryana', 'Haryana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Bihar', 'Bihar'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Puducherry', 'Puducherry'), ('Tamil Nadu', 'Tamil Nadu'), ('Daman and Diu', 'Daman and Diu'), ('Assam', 'Assam'), ('Tripura', 'Tripura')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
