# Generated by Django 3.2.12 on 2024-02-24 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20240217_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Puducherry', 'Puducherry'), ('Bihar', 'Bihar'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Karnataka', 'Karnataka'), ('Lakshadweep', 'Lakshadweep'), ('Gujarat', 'Gujarat'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Kerala', 'Kerala'), ('Chandigarh', 'Chandigarh'), ('Punjab', 'Punjab'), ('Maharashtra', 'Maharashtra'), ('Sikkim', 'Sikkim'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Meghalaya', 'Meghalaya'), ('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Haryana', 'Haryana'), ('West Bengal', 'West Bengal'), ('Rajasthan', 'Rajasthan'), ('Daman and Diu', 'Daman and Diu'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Tripura', 'Tripura'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Manipur', 'Manipur'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland')], max_length=100),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
