# Generated by Django 3.2.12 on 2024-02-27 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20240224_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Puducherry', 'Puducherry'), ('Assam', 'Assam'), ('Rajasthan', 'Rajasthan'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Goa', 'Goa'), ('Kerala', 'Kerala'), ('Chandigarh', 'Chandigarh'), ('Mizoram', 'Mizoram'), ('Delhi', 'Delhi'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka'), ('Nagaland', 'Nagaland'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Jharkhand', 'Jharkhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Tripura', 'Tripura'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Meghalaya', 'Meghalaya'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Manipur', 'Manipur'), ('Lakshadweep', 'Lakshadweep'), ('Telangana', 'Telangana'), ('Sikkim', 'Sikkim'), ('Punjab', 'Punjab'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Maharashtra', 'Maharashtra'), ('Odisha', 'Odisha'), ('Tamil Nadu', 'Tamil Nadu'), ('Haryana', 'Haryana'), ('Daman and Diu', 'Daman and Diu'), ('Gujarat', 'Gujarat'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
