# Generated by Django 3.2.12 on 2024-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240227_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Tripura', 'Tripura'), ('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('Meghalaya', 'Meghalaya'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Nagaland', 'Nagaland'), ('Manipur', 'Manipur'), ('Chhattisgarh', 'Chhattisgarh'), ('Puducherry', 'Puducherry'), ('Chandigarh', 'Chandigarh'), ('Assam', 'Assam'), ('Uttarakhand', 'Uttarakhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('West Bengal', 'West Bengal'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Sikkim', 'Sikkim'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Kerala', 'Kerala'), ('Telangana', 'Telangana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Odisha', 'Odisha'), ('Maharashtra', 'Maharashtra'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Delhi', 'Delhi'), ('Lakshadweep', 'Lakshadweep'), ('Tamil Nadu', 'Tamil Nadu'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('Karnataka', 'Karnataka'), ('Mizoram', 'Mizoram'), ('Rajasthan', 'Rajasthan'), ('Jharkhand', 'Jharkhand'), ('Bihar', 'Bihar')], max_length=100),
        ),
    ]
