# Generated by Django 3.2.12 on 2024-02-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240228_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Tripura', 'Tripura'), ('Mizoram', 'Mizoram'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Nagaland', 'Nagaland'), ('Himachal Pradesh', 'Himachal Pradesh'), ('West Bengal', 'West Bengal'), ('Maharashtra', 'Maharashtra'), ('Puducherry', 'Puducherry'), ('Lakshadweep', 'Lakshadweep'), ('Jharkhand', 'Jharkhand'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Telangana', 'Telangana'), ('Daman and Diu', 'Daman and Diu'), ('Sikkim', 'Sikkim'), ('Odisha', 'Odisha'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Goa', 'Goa'), ('Tamil Nadu', 'Tamil Nadu'), ('Manipur', 'Manipur'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Meghalaya', 'Meghalaya'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Assam', 'Assam'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Rajasthan', 'Rajasthan')], max_length=100),
        ),
    ]
